version: '3.6'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "5200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../flower-water/dist:/usr/share/nginx/html
    networks:
      - pi
networks:
  pi:
